stages:
  - test
  - build
  - release

test:
  stage: test
  image: python:3.8
  script:
    - echo "Running tests"
    - pip install -r ./src/requirements.txt
    - pip install -U pytest
    - pytest ./tests --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  only:
    - master

windows_build:
  stage: build
  image:
    name: batonogov/pyinstaller-windows:latest
    entrypoint: [""]
  script:
    - echo "Creating Windows artifact"
    - pip install -r ./src/requirements.txt
    - cd ./src && pyinstaller -F -c --add-data "./trackers/smi/iViewXAPI64.dll;." --add-data "./trackers/eyelogic/api/x64/*;./trackers/eyelogic/api/x64" --add-data "./trackers/eyelogic/api/x86/*;./trackers/eyelogic/api/x86" -n "develex-bridge" main.py
    - cp ./dist/*.exe ../
  after_script:
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
  needs:
    - test
  artifacts:
    paths:
      - "*.exe"
    when: always
    expire_in: never
    reports:
      dotenv: job.env
  only:
    - master

release_windows:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: windows_build
      artifacts: true
  script:
    - echo "Releasing Windows artifact $JOB_ID"
  release:
    name: "Release $CI_COMMIT_NAME"
    tag_name: $CI_COMMIT_NAME
    ref: $CI_COMMIT_NAME
    description: "Release for $CI_COMMIT_NAME"
    assets:
      links:
        - name: "develex-bridge.exe"
          url: "https://gitlab.ics.muni.cz/473783/develex-bridge/-/jobs/$JOB_ID/artifacts/file/develex-bridge.exe"
  only:
    - master
